### ISSUE TITLE
Line 2 of readme references wrong domain?

### ISSUE THREAD

**Issue by mwoolweaver** [pivpn/pivpn.io#5]
> `[Is pivpn.dev down?](https://p.datadoghq.com/sb/od1t7p4rmqi6x1fm-cd513e61b0eb77a5d5f6a52fe0662205?theme=dark)`

shouldn't this be for pivpn.io?

**Comment by coolapso** [comment]
Well it should ... but it actually is the same :) and both are held by us

**Comment by coolapso** [comment]
Done, Fixed it ... to clarify a bit better, there was a time where we maintainers didn't had control over the .io domain, and during a brief time we moved to .dev ... that has been solved a short while after and now we hold both .dev and .io domains, 

so if you try pivpn.dev you will be redirected to pivpn.io :) 

Thanks for the call out.

**Comment by mwoolweaver** [comment]
> to clarify a bit better, there was a time where we maintainers didn't had control over the .io domain, and during a brief time we moved to .dev

I do remember that

> so if you try pivpn.dev you will be redirected to pivpn.io

I did notice this as well. I just didn't want any confusion for potential new users

**Comment by coolapso** [comment]
you did well! thanks :D
