### ISSUE TITLE
 Raspbian Lite link dead

### ISSUE THREAD

**Issue by HansvdLaan** [pivpn/pivpn.io#7]
Hey,

The link to Raspbian Lite on the website is dead [1].  A possible solution might be to refer to https://raspberrypi.org/downloads (as on GitHub) or https://www.raspberrypi.org/software/operating-systems/.  All other links on the website are working. 

Thank you for your great project!

[1] see: [...] we strongly recommend using the latest **_Raspbian Lite_** image but [...]

**Comment by orazioedoardo** [comment]
Sorry for the delay, done. https://github.com/pivpn/pivpn.io/commit/17b7ce4944e5a52209e4de098bc19c20f386aede

**Comment by coolapso** [comment]
Infra picked up the changes, containers got updated. 

Thanks @orazioedoardo
