### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by alantbacon** [pivpn/pivpn.io#8]
In the “Contribute” section there’s a typo where ‘Plase’ should be ‘Please’. IMO the following ‘M’ shouldn’t be capitalized either :)

**Comment by orazioedoardo** [comment]
Done, thanks: https://github.com/pivpn/pivpn.io/commit/21cd9dffbd49ef84bebfb9e46e07ac25e7849ee9

**Comment by coolapso** [comment]
Infra picked up the changes, containers got updated.

Thanks @orazioedoardo
